"""Schnorr signatures: a clean discrete-log signature, and a ZK proof in disguise.

To sign, the signer proves they know the private key x behind the public key
X = g^x without revealing x. They pick a random nonce k, publish the commitment
R = g^k, derive a challenge c = H(R || X || message), and answer s = k + c*x. The
verifier checks g^s == R * X^c. It works because g^(k + c*x) = g^k * (g^x)^c.

This is a Sigma protocol — commit, challenge, respond — made non-interactive by
the Fiat-Shamir trick: replacing the verifier's random challenge with a hash.
The same three-move structure is the template behind most zero-knowledge proofs.

Two rules mirror ElGamal's: the nonce k must be fresh and secret every time
(reusing it, or leaking it, exposes x by simple algebra), and the challenge must
hash the message so signatures do not transfer between messages.

Educational, over a prime-field group; production Schnorr (BIP-340) uses an
elliptic curve. Use a vetted library.
"""

import hashlib
import secrets

# A prime p with a large prime-order subgroup of order q generated by g.
P = 0xFFFFFFFFFFFFFFFFC90FDAA22168C234C4C6628B80DC1CD129024E088A67CC74020BBEA63B139B22514A08798E3404DDEF9519B3CD3A431B302B0A6DF25F14374FE1356D6D51C245E485B576625E7EC6F44C42E9A63A3620FFFFFFFFFFFFFFFF
Q = (P - 1) // 2  # order of the subgroup of quadratic residues
G = 4  # 2^2 generates the QR subgroup of order Q


def keygen() -> tuple[int, int]:
    x = secrets.randbelow(Q - 1) + 1  # private
    return x, pow(G, x, P)  # (private, public)


def _challenge(r: int, pub: int, message: bytes) -> int:
    data = r.to_bytes(128, "big") + pub.to_bytes(128, "big") + message
    return int.from_bytes(hashlib.sha256(data).digest(), "big") % Q


def sign(message: bytes, x: int) -> tuple[int, int]:
    k = secrets.randbelow(Q - 1) + 1  # fresh nonce, MUST be secret and unique
    r = pow(G, k, P)
    c = _challenge(r, pow(G, x, P), message)
    s = (k + c * x) % Q
    return r, s


def verify(message: bytes, signature: tuple[int, int], pub: int) -> bool:
    r, s = signature
    c = _challenge(r, pub, message)
    # g^s should equal R * X^c.
    return pow(G, s, P) == r * pow(pub, c, P) % P


def main() -> None:
    x, pub = keygen()
    print(f"{P.bit_length()}-bit group, keypair generated")

    message = b"send 10 coins to Bob"
    signature = sign(message, x)
    print(f"signature (R, s): R={str(signature[0])[:16]}..., s={str(signature[1])[:16]}...")
    print(f"valid signature verifies: {verify(message, signature, pub)}")

    # Any tampering breaks it.
    print(f"tampered message rejected: {not verify(b'send 10 coins to Mallory', signature, pub)}")
    print(f"wrong public key rejected: {not verify(message, signature, keygen()[1])}")

    # Randomised: each signing uses a fresh nonce, so signatures differ.
    print(f"two signings differ (fresh nonce): {sign(message, x) != sign(message, x)}")

    # Nonce reuse is catastrophic: two signatures on different messages with the
    # same k let anyone solve for the private key.
    print("nonce reuse leaks the private key:")
    k = secrets.randbelow(Q - 1) + 1
    r = pow(G, k, P)
    m1, m2 = b"message one", b"message two"
    c1 = _challenge(r, pub, m1)
    c2 = _challenge(r, pub, m2)
    s1 = (k + c1 * x) % Q
    s2 = (k + c2 * x) % Q
    # s1 - s2 = (c1 - c2) * x  ->  x = (s1 - s2) / (c1 - c2) mod Q
    recovered = (s1 - s2) * pow(c1 - c2, -1, Q) % Q
    print(f"  recovered private key == real key: {recovered == x}")


if __name__ == "__main__":
    main()
